### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rtps#13]

**Comment by defunctzombie** [comment]
https://github.com/foxglove/studio/discussions/2355

**Comment by jtbandes** [comment]
We have deprecated the direct ROS 2 connection in Foxglove Studio in favor of our new `foxglove_bridge` WebSocket server, which provides more stability and a better user experience. As such we are no longer actively maintaining this package. You can find instructions to use the WebSocket bridge here: https://foxglove.dev/docs/studio/connection/ros2#live-connection
