### ISSUE TITLE
SubMessage coalescing

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rtps#21]
We currently send more UDP datagrams than are necessary, since there is no attempt to combine unrelated groups of submessages in single datagrams. Doing this requires some awareness of the SubMessages being grouped and where additional INFO_TS / INFO_DST SubMessages need to be injected, implying some refactoring to the SubMessageGroup concept.

**Comment by jtbandes** [comment]
We have deprecated the direct ROS 2 connection in Foxglove Studio in favor of our new `foxglove_bridge` WebSocket server, which provides more stability and a better user experience. As such we are no longer actively maintaining this package. You can find instructions to use the WebSocket bridge here: https://foxglove.dev/docs/studio/connection/ros2#live-connection
