### ISSUE TITLE
CycloneDDS crashes when subscribing to a topic with large messages

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rtps#22]
**Description**

When using @foxglove/rtps as a subscriber to a topic published by CycloneDDS with large messages, in the right environment CycloneDDS will crash with the following error:

```
Error:
[cam-2] python3: /tmp/binarydeb/ros-galactic-cyclonedds-0.8.0/src/core/ddsi/src/ddsi_entity_index.c:411: entidx_lookup_proxy_reader_guid: Assertion `is_reader_entityid (guid->entityid)' failed.
[ERROR] [cam-2]: process has died [pid 3848, exit code -6, cmd '/home/sh/ws/flir-wrapper_ws/install/flir_wrapper/lib/flir_wrapper/cam --ros-args -r __node:=cam_727 -r __ns:=/cam_727 --params-file /tmp/launch_params_5fvheszt'].
```

This can be reproduced on an Ubuntu 20.04 desktop running ROS Galactic with the default CycloneDDS RMW and a ROS 2 node publishing topics from a RealSense D435i.

**Comment by felixf4xu** [comment]
I'd like to share what I have found so far:

during the ros2 node crash, the call stack is:
```
libddsc.so.0!entidx_lookup_proxy_reader_guid(const struct entity_index * ei, const struct ddsi_guid * guid) (\home\someone\github\cyclonedds\src\core\ddsi\src\ddsi_entity_index.c:412)
libddsc.so.0!handle_NackFrag(struct receiver_state * rst, ddsrt_etime_t tnow, const NackFrag_t * msg, SubmessageKind_t prev_smid, struct defer_hb_state * defer_hb_state) (\home\someone\github\cyclonedds\src\core\ddsi\src\q_receive.c:1556)
libddsc.so.0!handle_submsg_sequence(struct thread_state1 * const ts1, struct ddsi_domaingv * gv, ddsi_tran_conn_t conn, const ddsi_locator_t * srcloc, ddsrt_wctime_t tnowWC, ddsrt_etime_t tnowE, const ddsi_guid_prefix_t * const src_prefix, const ddsi_guid_prefix_t * const dst_prefix, unsigned char * const msg, const size_t len, unsigned char * submsg, struct nn_rmsg * const rmsg, _Bool rtps_encoded) (\home\someone\github\cyclonedds\src\core\ddsi\src\q_receive.c:3013)
libddsc.so.0!do_packet(struct thread_state1 * const ts1, struct ddsi_domaingv * gv, ddsi_tran_conn_t conn, const ddsi_guid_prefix_t * guidprefix, struct nn_rbufpool * rbpool) (\home\someone\github\cyclonedds\src\core\ddsi\src\q_receive.c:3295)
libddsc.so.0!recv_thread(void * vrecv_thread_arg) (\home\someone\github\cyclonedds\src\core\ddsi\src\q_receive.c:3510)
libddsc.so.0!create_thread_wrapper(void * ptr) (\home\someone\github\cyclonedds\src\core\ddsi\src\q_thread.c:241)
libddsc.so.0!os_startRoutineWrapper(void * threadContext) (\home\someone\github\cyclonedds\src\ddsrt\src\threads\posix\threads.c:165)
libpthread.so.0!start_thread(void * arg) (\build\glibc-SzIz7B\glibc-2.31\nptl\pthread_create.c:477)
libc.so.6!clone() (\build\glibc-SzIz7B\glibc-2.31\sysdeps\unix\sysv\linux\x86_64\clone.S:95)
```
in function of `handle_submsg_sequence()`, the `sm->smhdr.submessageId` is `(enum SubmessageKind)SMID_NACK_FRAG = 18`.

in function of `int is_reader_entityid (ddsi_entityid_t id)`, id.u is: 0x0

normal case:
```
sm->smhdr.submessageId is: 14
sm->smhdr.submessageId is: 6
is_reader_entityid returns 4, id.u is: 0x1404
is_reader_entityid returns 4, id.u is: 0x304
is_reader_entityid returns 4, id.u is: 0x404
sm->smhdr.submessageId is: 14
```
crash case:
```
sm->smhdr.submessageId is: 18
is_reader_entityid returns 0, id.u is: 0x0
```

from code `src.entityid = msg->readerId;`, I can find that `msg->readerId.u` is 0 then the node crashes, only at case of SMID_NACK_FRAG.

I may need help from here.

**Comment by felixf4xu** [comment]
just by coincidence, if I run
```sh
sudo sysctl -w net.core.rmem_max=26214400
sudo sysctl -w net.core.rmem_default=26214400
sudo sysctl -w net.ipv4.udp_mem=26214400
```
as shown in the readme, the crash is gone!!

I'm not sure if this is _expected_ or _bug_.

Anyway, if someone is trying to reproduce the bug, don't change the udp configurations, then it can be reproduced almost every time!

**Comment by jhurliman** [comment]
@felixf4xu I believe the crash is related to @foxglove/rtps sending one or more NACK_FRAG packets, which are sent when there is packet loss. Packet loss happens with large RTPS messages and the default Ubuntu (18/20/22) kernel UDP receive buffer size. If there's no packet loss, there's no bug.

**Comment by felixf4xu** [comment]
I would like to debug into this, but a very stupid question first: how to compile a debug version of foxglove/rtps along with foxglove/studio (or any other way to compile my local foxglove/rtps into a running foxglove/studio)?

I have checked foxglove/studio's source code a little bit, but I didn't find any dependencies of foxglove/rtps, only one line of code 
```ts
import { Durability, Reliability } from "@foxglove/rtps";
```
it's weird, would `yarn` automatically detect the dependency of `foxglove/rtps`?

**Comment by jhurliman** [comment]
@felixf4xu I think the "correct" answer here involves `yarn link`. Since Studio uses yarn v2 and @foxglove/ros2 + @foxglove-rtps use yarn v1 I have run into problems with this workflow before, and ended up running `yarn build` in @foxglove/rtps then copying the `dist/` output into the `node_modules/@foxglove/rtps` folder of Studio then rebuilding with `yarn desktop:serve`. Very hacky.

A better approach that makes debugging this much easier is to ignore Studio and connect directly to your ROS 2 DDS network using the `@foxglove/rtps` package. The example script at https://github.com/foxglove/rtps/blob/main/examples/listener.ts can be tweaked to subscribe to the topic you are using to reproduce the crash.

**Comment by jtbandes** [comment]
We have deprecated the direct ROS 2 connection in Foxglove Studio in favor of our new `foxglove_bridge` WebSocket server, which provides more stability and a better user experience. As such we are no longer actively maintaining this package. You can find instructions to use the WebSocket bridge here: https://foxglove.dev/docs/studio/connection/ros2#live-connection
